# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('list_item', 'text')]),
        ),
    ]
